#!/usr/bin/env python3
"""Generate the GitLab child pipeline for the build matrix.

Reads build_matrix.json (written by scripts/check_app_updates.py) and emits:
- build.env: dotenv file with HAS_UPDATES=true/false for the parent pipeline.
- build-child.yml: a child pipeline with one build job per matrix entry plus
  a release job that publishes everything to the GitLab 'latest' release.

The build jobs extend the shared template in .gitlab/build-template.yml.
"""
import json
import re
import sys
from pathlib import Path

MATRIX_FILE = Path("build_matrix.json")
CHILD_FILE = Path("build-child.yml")
ENV_FILE = Path("build.env")


def job_name(entry: dict) -> str:
    raw = f"build-{entry['app_name']}-{entry['source']}-{entry['arch']}"
    return re.sub(r"[^a-zA-Z0-9_]+", "-", raw).strip("-").lower()


def main() -> int:
    matrix = json.loads(MATRIX_FILE.read_text()) if MATRIX_FILE.exists() else []
    has_updates = bool(matrix)
    ENV_FILE.write_text(f"HAS_UPDATES={'true' if has_updates else 'false'}\n")
    print(f"HAS_UPDATES={'true' if has_updates else 'false'} ({len(matrix)} jobs)")

    if not has_updates:
        CHILD_FILE.write_text("# no updates; empty child pipeline\n")
        return 0

    # Stash new_manifest.json where the child release job can fetch it
    # (child pipelines cannot see the parent's job artifacts).
    manifest_src = Path("new_manifest.json")
    if manifest_src.exists():
        from src import gitlab_api
        gitlab_api.upload_package_file(manifest_src, package="morphe-meta",
                                       version="latest")
        print("Uploaded new_manifest.json to morphe-meta package")

    names = [job_name(e) for e in matrix]
    lines = [
        "# AUTO-GENERATED by scripts/gitlab_child_pipeline.py - do not edit",
        "include:",
        "  - local: '.gitlab/build-template.yml'",
        "",
        "stages: [build, release]",
        "",
    ]
    for entry, name in zip(matrix, names):
        lines += [
            f"{name}:",
            "  extends: .morphe-build",
            "  stage: build",
            "  variables:",
            f"    APP_NAME: \"{entry['app_name']}\"",
            f"    SOURCE: \"{entry['source']}\"",
            f"    ARCH: \"{entry['arch']}\"",
            "",
        ]
    needs = "\n".join(f"    - job: {n}\n      optional: true" for n in names)
    lines += [
        "publish-release:",
        "  extends: .morphe-release",
        "  stage: release",
        "  needs:",
        needs,
        "",
    ]
    CHILD_FILE.write_text("\n".join(lines))
    print(f"Wrote {CHILD_FILE} with {len(names)} build jobs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
